# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'RxSwiftExercise' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftExercise
  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'

  target 'RxSwiftExerciseTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '6.2.0'
    pod 'RxTest', '6.2.0'
  end

  target 'RxSwiftExerciseUITests' do
    # Pods for testing
  end

end
